[build]
  command = "npm i -g pnpm && pnpm install && pnpm run build:landing"
  publish = "apps/landing-page/dist"
  base = "/"

[build.environment]
  NPM_FLAGS = "--no-audit --no-fund"
  PNPM_FLAGS = "--shamefully-hoist"
