-- AlterTable
ALTER TABLE `EmployeeTraining` ADD COLUMN `employeeNotes` TEXT NULL,
    MODIFY `status` ENUM('ASSIGNED', 'ACCEPTED', 'IN_PROGRESS', 'COMPLETED', 'REJECTED') NOT NULL DEFAULT 'ASSIGNED';
