export enum Role {
    ADMIN = 'ADMIN',
    MANAGER = 'MANAGER',
    EMPLOYEE = 'EMPLOYEE',
    OWNER = 'OWNER',
}

export enum Permission {
    VIEW_DASHBOARD = 'VIEW_DASHBOARD',
    MANAGE_USERS = 'MANAGE_USERS',
    MANAGE_COMPANIES = 'MANAGE_COMPANIES',
    MANAGE_RECRUITMENT = 'MANAGE_RECRUITMENT',
    VIEW_REPORTS = 'VIEW_REPORTS',
}
